### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by PoplarYang** [nielsAD/autoindex#1]
When I try to build it, I meet the problem:
```bash
walk/getdents_unix.go:54:13: undefined: syscall.Getdents

➜  ~ go version
go version go1.14 darwin/amd64
```

https://github.com/nielsAD/autoindex/blob/2ef921b14963226c5b38fef7b6b8806e73125240/walk/getdents_unix.go#L54

**Comment by nielsAD** [comment]
Thanks for reporting, there was a building issue for macOS.
