### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by Pfuenzle** [nielsAD/autoindex#3]
Hello,

everytime I try to server a directory, I get the error `404 page not found` when accessing it via a browser.

The commands I used are 
`./autoindex -a="0.0.0.0:4000" -r=/mnt/mydir`

and 

`./autoindex -a=":4000" -i=1m -d=/tmp/autoindex.db -r=/mnt/mydir`

The directory exists and is fully read- and writable by the user.
I alsy tried to run it under root, same thing.
I used version 1.0 from the release page on Debian 10.

The log output shows nothing except
`Serving files in '/mn/mydir' on 0.0.0.0:4000
2357 records in database after update (+2357)`

Really looking forward to it, the demo looked great

**Comment by hansbogert** [comment]
try 

```
$ curl host:40000/idx
```

/update

actually.. that's not the intended url at all, disregard this.

**Comment by hansbogert** [comment]
You need to copy the public folder from the repo, to your working directory, in your example: `r=/mnt/mydir`. So you should have a directory `/mnt/mydir/public`.

**Comment by nielsAD** [comment]
Good catch! I have added the `public` folder back to the release archives, let me know if that fixes it for you!

**Comment by Pfuenzle** [comment]
Yes, it's working perfectly now.
Thanks a lot for the fast help both of you :(
And thanks a lot for this tool, this is exactly what I have been looking for for a while.
