### ISSUE TITLE
Windows release marked as malware

### ISSUE THREAD

**Issue by nollium** [nielsAD/autoindex#5]
Hello,

Just so you know, the windows release build is marked as malware by windows defender.
Screenshot attached.

![image](https://user-images.githubusercontent.com/54525684/158457541-8a4b23ab-7993-4df3-a37f-d0e1f9b48b16.png)

**Comment by nielsAD** [comment]
Thanks for the report. Looks like [both](https://www.virustotal.com/gui/file/ca7cf40f79cc51e37b9f3e056913a542a227cfc22d0adc421abbb98581e3bb34) Microsoft Defender and Elastic Security mark it as malicious. Not sure what's causing it.

I've submitted a false positive report to Microsoft, but might also play around with the build configuration to see if I can find out what's causing it.

**Comment by nielsAD** [comment]
Microsoft confirmed it was a false positive and Defender will stop showing it as malware after an update. I've also submitted a false positive report to Elastic Security, but do not expect a similarly quick response there.

**Comment by nielsAD** [comment]
I haven't heard back yet from Elastic, so I'll close this for now.
